Repository maaaathis/digga, pull requests merged in 2024-01, with the labels that each got.

#61 add drawer for mobile view of ipDetailsModal
  components/IpDetailsModal.tsx
  components/ui/drawer.tsx
  hooks/use-media-query.tsx
  package.json
  yarn.lock
Labels: enhancement, size/L

#60 feat: Add new technologies widget for overview
  app/lookup/[domain]/page.tsx
  components/TechnologiesDetailsModal.tsx
  components/overview/TechnologiesWidget.tsx
  next.config.js
Labels: enhancement, size/L

#63 improve links in technologies list
  components/TechnologiesDetailsModal.tsx
  components/overview/TechnologiesWidget.tsx
Labels: size/S

#65 improve placing of technologies icons
  components/TechnologiesDetailsModal.tsx
  components/overview/TechnologiesWidget.tsx
Labels: size/XS

#66 improve placing of domaindates at mobile devices
  components/overview/DomainDatesWidget.tsx
Labels: size/XS

#67 fix tech widget spacing on mobile devices
  components/overview/TechnologiesWidget.tsx
Labels: bug, size/XS

#68 fix: domainlabel link not set fails
  components/overview/DomainlabelWidget.tsx
Labels: bug, size/S

#70 refactor: optimize locationMap height on mobile devices
  components/IpDetailsModal.tsx
Labels: size/XS

#69 refactor: use direct links for technology details
  components/TechnologiesDetailsModal.tsx
  components/overview/TechnologiesWidget.tsx
Labels: size/S

#71 optimize whois fetching & disable next.js image optimization
  app/lookup/[domain]/page.tsx
  components/ExternalFavicon.tsx
  components/TechnologiesDetailsModal.tsx
  components/overview/DomainDatesWidget.tsx
  components/overview/DomainOwnerInfoWidget.tsx
  components/overview/DomainlabelWidget.tsx
  components/overview/NameserverWidget.tsx
  components/overview/TechnologiesWidget.tsx
Labels: size/M

#72 feat: focus search input by hotkey
  components/SearchForm.tsx
Labels: enhancement, size/XS

#73 use swr/immutable
  components/IpDetailsModal.tsx
Labels: size/XS

#75 optimize seo
  app/layout.tsx
  app/page.tsx
Labels: size/M

#76 fix: tech widget ui when there are more than 4 domainlabels
  components/overview/TechnologiesWidget.tsx
Labels: size/M

#77 add link to ICANN whois lookup
  app/lookup/[domain]/whois/page.tsx
Labels: enhancement, size/S

#78 add detail link to certs page
  app/lookup/[domain]/certs/page.tsx
Labels: enhancement, size/L

#82 adjust autocompletion & correction in SearchForm
  components/SearchForm.tsx
Labels: size/XS

#84 improve accessibility on header & footer
  components/CreditsInfo.tsx
  components/Header.tsx
  components/ThemeMenu.tsx
Labels: size/S

#89 bump tailwindcss to 3.4.1
  package.json
  yarn.lock
Labels: bug, dependencies, size/S

#90 remove bottleneck
  package.json
  utils/DnsLookup.ts
  yarn.lock
Labels: dependencies, size/S

#91 Improve dns lookup logic & add Cloudflare and Google resolver
  app/lookup/[domain]/dns/page.tsx
  components/DnsTable.tsx
  components/RecordRow.tsx
  components/ResolverSelector.tsx
  components/overview/DnsRecordsWidget.tsx
  components/ui/select.tsx
  lib/resolvers/AuthoritativeResolver.ts
  lib/resolvers/CloudflareDoHResolver.ts
  lib/resolvers/DnsResolver.ts
  lib/resolvers/GoogleDoHResolver.ts
  package.json
  yarn.lock
Labels: enhancement, size/XL

#92 Fix non-requested types being returned by DoH
  lib/resolvers/CloudflareDoHResolver.ts
  lib/resolvers/GoogleDoHResolver.ts
Labels: bug, size/M

#93 Improve lightmode color of background grid
  app/layout.tsx
Labels: size/XS

#94 Optimize background grid at lightmode
  app/layout.tsx
Labels: size/XS

#95 Fix DNS resolver picker not being visible without results
  app/lookup/[domain]/dns/page.tsx
Labels: size/S

#100 Improve WHOIS error handling if no data is available
  app/lookup/[domain]/whois/page.tsx
  components/StyledError.tsx
Labels: size/M

#102 Add DNS resolver location selector
  app/api/internal/resolve/arn/route.ts
  app/api/internal/resolve/base.ts
  app/api/internal/resolve/bom/route.ts
  app/api/internal/resolve/cdg/route.ts
  app/api/internal/resolve/cle/route.ts
  app/api/internal/resolve/cpt/route.ts
  app/api/internal/resolve/dub/route.ts
  app/api/internal/resolve/fra/route.ts
  app/api/internal/resolve/gru/route.ts
  app/api/internal/resolve/hkg/route.ts
  app/api/internal/resolve/hnd/route.ts
  app/api/internal/resolve/iad/route.ts
  app/api/internal/resolve/icn/route.ts
  app/api/internal/resolve/kix/route.ts
  app/api/internal/resolve/lhr/route.ts
  app/api/internal/resolve/pdx/route.ts
  app/api/internal/resolve/sfo/route.ts
  app/api/internal/resolve/sin/route.ts
  app/api/internal/resolve/syd/route.ts
  app/globals.css
  app/lookup/[domain]/dns/page.tsx
  components.json
  components/LocationSelector.tsx
  components/ResolverSelector.tsx
  lib/data.ts
  lib/resolvers/InternalDoHResolver.ts
  package.json
  tailwind.config.js
  yarn.lock
Labels: enhancement, size/L

#106 Add Alibaba Public DNS DoH resolver
  app/api/internal/resolve/base.ts
  app/lookup/[domain]/dns/page.tsx
  components/ResolverSelector.tsx
  lib/resolvers/AlibabaDoHResolver.ts
  lib/resolvers/InternalDoHResolver.ts
Labels: enhancement, size/M

#111 Optimize handling with Sub- & SubSubDomains and catch TechWidget errors
  app/lookup/[domain]/certs/page.tsx
  app/lookup/[domain]/page.tsx
  app/lookup/[domain]/whois/page.tsx
  components/overview/TechnologiesWidget.tsx
  lib/utils.ts
Labels: size/M

#112 Use Cloudflare DoH resolver on overview cards
  app/lookup/[domain]/dns/page.tsx
  components/overview/DnsRecordsWidget.tsx
Labels: enhancement, size/XS

#115 only show whois-related widgets if whoisData fetched successfully
  app/lookup/[domain]/page.tsx
Labels: size/M

#116 check for invalid domain whois date formatting
  components/overview/DomainDatesWidget.tsx
Labels: size/S

#117 add support for .ch tlds
  app/lookup/[domain]/dns/page.tsx
  app/lookup/[domain]/page.tsx
  app/lookup/[domain]/whois/page.tsx
  components/StyledError.tsx
  components/overview/DomainlabelWidget.tsx
  components/overview/NameserverWidget.tsx
  lib/utils.ts
  lib/whois.ts
Labels: enhancement, size/L

#118 Refactor ResultsTab & remove shortcut on mobile devices
  components/ResultsTabs.tsx
Labels: enhancement, size/L

#119 add DNSSEC info badge
  app/api/internal/whois/route.ts
  components/DNSSECinfo.tsx
  components/overview/DashboardItem.tsx
  components/overview/NameserverWidget.tsx
  tailwind.config.js
Labels: enhancement, size/L

#120 add logo background on hover
  components/Header.tsx
Labels: size/XS

#121 Revert "check for invalid domain whois date formatting"
  components/overview/DomainDatesWidget.tsx
Labels: bug, size/S

#122 Improve overall stability
  app/error.tsx
  app/lookup/[domain]/layout.tsx
  app/lookup/[domain]/loading.tsx
  app/lookup/not-found.tsx
  components/overview/DashboardItem.tsx
  components/overview/DnsRecordsWidget.tsx
  components/overview/DomainOwnerInfoWidget.tsx
  components/overview/NameserverWidget.tsx
  components/overview/TechnologiesWidget.tsx
  lib/utils.ts
Labels: enhancement, size/L

#123 make link in whois error page more visible
  app/lookup/[domain]/whois/page.tsx
  components/IpDetailsModal.tsx
Labels: size/S

#125 Use SearchIcon on SearchForm button on mobile devices
  components/SearchForm.tsx
Labels: enhancement, size/S

#129 Redesign ThemeMenu & CreditsInfo
  app/globals.css
  app/layout.tsx
  app/lookup/[domain]/layout.tsx
  app/providers.tsx
  components/CreditsInfo.tsx
  components/Footer.tsx
  components/Header.tsx
  components/ThemeMenu.tsx
  components/ThemeToggle.tsx
  components/ui/button.tsx
  hooks/use-media-query.ts
  hooks/use-mounted.ts
  package.json
  tailwind.config.js
  yarn.lock
Labels: size/XXL

#137 Refactor components & overview structure
  app/lookup/[domain]/(overview)/_components/DNSSECinfo.tsx
  app/lookup/[domain]/(overview)/_components/DashboardItem.tsx
  app/lookup/[domain]/(overview)/_components/DnsRecordsWidget.tsx
  app/lookup/[domain]/(overview)/_components/DomainDatesWidget.tsx
  app/lookup/[domain]/(overview)/_components/DomainOwnerInfoWidget.tsx
  app/lookup/[domain]/(overview)/_components/DomainlabelWidget.tsx
  app/lookup/[domain]/(overview)/_components/NameserverWidget.tsx
  app/lookup/[domain]/(overview)/_components/RecordList.tsx
  app/lookup/[domain]/(overview)/_components/TechnologiesDetailsModal.tsx
  app/lookup/[domain]/(overview)/_components/TechnologiesWidget.tsx
  app/lookup/[domain]/(overview)/loading.tsx
  app/lookup/[domain]/(overview)/page.tsx
  app/lookup/[domain]/dns/_components/DnsTable.tsx
  app/lookup/[domain]/dns/_components/IpDetailsModal.tsx
  app/lookup/[domain]/dns/_components/IpLink.tsx
  app/lookup/[domain]/dns/_components/LocationMap.tsx
  app/lookup/[domain]/dns/_components/LocationSelector.tsx
  app/lookup/[domain]/dns/_components/RecordRow.tsx
  app/lookup/[domain]/dns/_components/ResolverSelector.tsx
  app/lookup/[domain]/dns/page.tsx
  components/ResultsTabs.tsx
Labels: size/M

#138 bump next.js to 14.1.0
  package.json
  yarn.lock
Labels: dependencies

#139 Optimize DNS resolving
  lib/resolvers/AuthoritativeResolver.ts
  lib/resolvers/InternalDoHResolver.ts
  lib/utils.ts
Labels: size/M

#140 use node:20
  .github/workflows/test.yml
  package.json
Labels: dependencies, size/XS

#141 extend isAvailable check to whois DomainStatus = AVAILABLE (for ex. .it tlds)
  lib/whois.ts
Labels: bug, enhancement, size/XS

#142 Resolve canonical urls correctly
  app/lookup/[domain]/(overview)/page.tsx
  app/lookup/[domain]/certs/page.tsx
  app/lookup/[domain]/dns/page.tsx
  app/lookup/[domain]/layout.tsx
  app/lookup/[domain]/whois/page.tsx
  app/page.tsx
Labels: size/M

#143 add support for .li tlds
  app/lookup/[domain]/whois/page.tsx
  lib/whois.ts
Labels: size/S

#144 bump actions & add open source badge
  .github/workflows/test.yml
  app/page.tsx
Labels: dependencies, size/S

#145 show search shortcut visually
  components/ResultsTabs.tsx
  components/SearchForm.tsx
  lib/utils.ts
Labels: size/M
